### ISSUE TITLE
También funciona con grupos con distinto padre

### ISSUE THREAD

**Issue by HeronFlight** [18turbo/OrdenacionRapida#1]
Hola, primero de todo, muchas gracias por estas macros para freecad.
He estado jugando un poco con la macro y me di cuenta que también funciona con grupos con distinto padre, aunque el comportamiento es un tanto aleatorio.
Invertigando en el código (soy principiante), vi que en la linea 38 defines la variable "padreDistinto", mientras que en el "if" de la linea 47, la variable es "distintoPadre", al igual que en la linea 28 donde defines la variale por primera vez.
Si cambio la variable de la linea 38 por "distintoPadre", entonces ya no deja ordenar grupos con distinto padre, entra en el último "else" y nos da el mensaje de "Debes seleccionar Grupos con el mismo padre".
No sé si esto es un error, o está hecho a propósito para algún futuro cambio. Si es un error, yo podría enviar un PR para corregirlo, o mejor dicho, podría intentarlo pues sería mi primer PR (tb soy principiante con github).

**Comment by 18turbo** [comment]
Hola HeronFlight,

Acabo de ver tu mensaje, pero seguro que es un fallo. Mañana lo miraré y ya te digo, pero haz el PR sin problemas. Yo me puse con el Github a raíz de las macros en FreeCAD, así que no sé quién será más novato jajaja.

En cualquier caso, gracias por revisarlo.

Un saludo.

**Comment by 18turbo** [comment]
Lo he podido mirar en unos minutos, y es un error claramente. Por eso hace la ordenación cuando tienen distinto padre, cuando no debería hacerlo.

Gracias

**Comment by HeronFlight** [comment]
Ok Rafael,
pues ya está lanzado el PR.
Gracias por dejarme practicar :-)

**Comment by 18turbo** [comment]
jejeje De nada, ya está aceptado el Merge.

Gracias a ti, un saludo
